[package]
name = "thash"
version = "0.1.0"
edition = "2021"

[dependencies]
hashing-lib = { path = "hashing-lib" }

anyhow = "1.0"
base64 = "0.22"
clap = { version = "4.5", features = ["derive"] }
hex = "0.4"
strum = "0.26"
strum_macros = "0.26"
