name: build

on:
  push:
    branches:
      - "**" # target all branches
  pull_request:
    branches:
      - "**" # target all branches

env:
  CARGO_TERM_COLOR: always

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Tests in terminal
        run: bash test-tools/run-cmd-tests.sh

  build_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Tests in terminal
        run: bash test-tools/run-cmd-tests.sh

  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Tests in terminal
        shell: bash
        run: ./test-tools/run-cmd-tests.sh
